name: dbt Cloud CICD
on:
  push:
    paths:
      - dbt-project/**
  pull_request:
    paths:
      - dbt-project/**

permissions:
  contents: read

jobs:
  test-macros:
    name: Test dbt Macros
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt-project
    env:
      SNOWFLAKE_USERNAME: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ACCOUNTNAME: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: dbt-dataverse/.python-version

      - name: Install dependencies
        run: uv sync

      - name: Install dbt dependencies
        run: uv run dbt deps

      - name: Run Ruff Linting
        run: uv run ruff check

      - name: Run SQLFluff Linting
        run: uv run sqlfluff lint models

      - name: Run PyTest Tests
        run: uv run pytest 
  
